name: Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/setup-python@v6.3.0
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements-dev.txt black

      - name: black --check
        run: black --check .

      - name: pytest
        run: pytest tests/ -v
